config/routes.rb
Rails.application.routes.draw do
  root 'shoes#index'

  resources :shoes, only: :index
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :shoes, dependent: :destroy

  validates :name,   presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shoe

  has_attached_file :picture,
    styles: { thumb: '370x200>' },
    default_url: "photo/missing.png"
  validates_attachment :picture,
    content_type: {content_type: /\Aimage\/.*\Z/},
    size: { in: 0..5.megabytes, message: 'Photo size too large. Please limit to 5 mbs.' }

  validates_attachment_presence :picture, presence: true
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :brand

  validates :name, presence: true
  validates :sku, presence: true
  validates :price, numericality: { greater_than: 0, allow_blank: true }

  has_attached_file :picture,
    styles: { thumb: '300x300#>' },
    default_url: "shoes/missing.png"
  validates_attachment :picture,
    content_type: {content_type: /\Aimage\/.*\Z/},
    size: { in: 0..5.megabytes, message: 'Photo size too large. Please limit to 5 mbs.' }

  def self.find_by_brands(brand_ids)
    where(brand: brand_ids)
  end

  def self.find_by_min_price(min_price)
    where("price >= ?", min_price)
  end

  def self.find_by_max_price(max_price)
    where("price <= ?", max_price)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @shoe_filter = ShoeFilter.new(shoes_search_params, cookies[:shoes_sort])
    @shoes       = @shoe_filter.result
    @shoes       = @shoes.paginate(page: params[:page], per_page: 18)
  end

  private

  def shoes_search_params
    return nil if params[:shoe_filter].nil?
    params[:shoe_filter].permit(
                                  :min_price,
                                  :max_price,
                                  :brand_ids => []
                                  )
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class WillPaginateJSLinkRenderer < WillPaginate::ActionView::LinkRenderer
    def prepare(collection, options, template)
      options[:params] ||= {}
      options[:params]['_'] = nil
      super(collection, options, template)
    end

    protected
    def link(text, target, attributes = {})
      if target.is_a? Fixnum
        attributes[:rel] = rel_value(target)
        target = url(target)
      end

      @template.link_to(target, attributes.merge(remote: true)) do
        text.to_s.html_safe
      end
    end
  end

  def js_will_paginate(collection, options = {})
    will_paginate(collection, options.merge(:renderer => WillPaginateHelper::WillPaginateJSLinkRenderer))
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'shared/head'
  body
    header
      = render 'shared/header'
    main
      = yield
    footer
      = render 'shared/footer'

app/views/shared/_footer.html.slim
.shared-footer-container
  .container
    #footer-logo-wrap
      = link_to image_tag("shared/footer-logo.png"), root_path
    .menu-wrap
      ul 
        li Conditions of Use
        li Privacy Notice
        li Interest-Based Ads
        li © 1996-2016, Sport.com

app/views/shared/_head.html.slim
meta content="width=device-width, initial-scale=1" name="viewport" /
title Shoes shopping

= stylesheet_link_tag    'application', media: 'all'
= javascript_include_tag 'application'
= csrf_meta_tags

app/views/shared/_header.html.slim
.shared-header-container
  .container
    .row
      = image_tag 'shared/logo'
  .top-menu
    .container
      .row
        .col.s4
          = image_tag 'shared/free-shipping'
        .col.s4
          = image_tag 'shared/free-return'
        .col.s4
          = image_tag 'shared/secure-payment'

app/views/shoes/_list.html.slim
.shoes-list-container
  - if shoes.present?
    - shoes.in_groups_of(3,false) do |items|
      .row
        - items.each do |shoe|
          .col.s4
            = render partial: "shoes/shoe", locals: { shoe: shoe }
    = js_will_paginate shoes, previous_label: "<i class='fa fa-chevron-left'></i>", next_label: "<i class='fa fa-chevron-right'></i>"        

app/views/shoes/_search.html.slim
.shoes-search-container
  = simple_form_for ShoeFilter.new(params[:shoe_filter]), url: shoes_path, remote: true, html: { method: :get } do |f|
    .title Refine by
    .filter-by-brand
      p Brands
      .brands-group
        = f.collection_check_boxes :brand_ids, Brand.all.map{ |b| [b.id, b.name] }, :first, :last
      p Price
      .price
        #price_slider
        = f.input :min_price, as: :hidden
        = f.input :max_price, as: :hidden 

app/views/shoes/_shoe.html.slim
.shoes-shoe-container
  .thumb 
    = image_tag shoe.picture.url(:thumb)
  .name = shoe.name
  .sku = shoe.sku
  .price = shoe.price
  .add_to_cart
    button.waves-effect.waves-light
      span == "<i class='fa fa-shopping-cart' aria-hidden='true'></i> Add to cart"

app/views/shoes/index.html.slim
#shoes-index-container
  .container
    .row
      .col.s3.container-left
        = render 'search'
      .col.s9.container-right
        .banner
          = image_tag 'shared/banner'
        .shoes-top
          .row
            .col.s6
              .num-of-shoes
                span.number = @shoes.size 
                span  matching shoes
            .col.s6
              .sort.right
                span.title Sort by:
                span.asc_desc = select_tag :shoe_sort, options_for_select([["DESC", "desc"], ["ASC", "asc"]]), include_blank: 'Alphabetical'
        #shoes-wrap
          = render partial: "list", locals: { shoes: @shoes }

coffee:
  sort_change();          

app/views/shoes/index.js.erb
$("#shoes-wrap").html("<%= j render partial: 'shoes/list', locals: { shoes: @shoes } %>");
$(".number").html("<%= @shoes.size %>");